// Auto-generated by credential-code
// DO NOT EDIT - This file will be overwritten

package com.example.credentials;

import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

public final class Credentials {
    public enum CredentialKey {
        API_KEY,
        AWS_SECRET_KEY,
        DATABASE_URL,
        JWT_SECRET,
        STRIPE_KEY
    }

    private static class EncryptedData {
        final byte[] data;
        final byte[] nonce;
        final byte[] tag;
        
        EncryptedData(byte[] data, byte[] nonce, byte[] tag) {
            this.data = data;
            this.nonce = nonce;
            this.tag = tag;
        }
    }
    
    private static final Map<CredentialKey, EncryptedData> encryptedData;
    private static final byte[][] keyComponents;
    
    static {
        // Initialize encrypted data
        encryptedData = new HashMap<>();
        encryptedData.put(CredentialKey.API_KEY, new EncryptedData(
            new byte[]{
                (byte)0x58, (byte)0x50, (byte)0x1D, (byte)-85, (byte)0x6A, (byte)0x3B,
                (byte)-11, (byte)-31, (byte)0x75, (byte)0x69, (byte)0x32, (byte)0x0B,
                (byte)-15, (byte)-111, (byte)-64, (byte)-112, (byte)-37, (byte)0x3C,
                (byte)0x2A, (byte)0x2B, (byte)-109, (byte)0x28, (byte)0x67, (byte)-108
            },
            new byte[]{
                (byte)0x14, (byte)0x02, (byte)0x5D, (byte)0x04, (byte)-8, (byte)0x3A,
                (byte)-35, (byte)0x1E, (byte)0x5A, (byte)0x67, (byte)0x4A, (byte)0x1A
            },
            new byte[]{
                (byte)0x20, (byte)-61, (byte)0x64, (byte)0x05, (byte)-80, (byte)0x69,
                (byte)0x32, (byte)0x77, (byte)-15, (byte)0x53, (byte)-65, (byte)0x43,
                (byte)0x6A, (byte)0x16, (byte)-109, (byte)0x16
            }
        ));
        encryptedData.put(CredentialKey.AWS_SECRET_KEY, new EncryptedData(
            new byte[]{
                (byte)0x46, (byte)-103, (byte)0x25, (byte)0x56, (byte)-110, (byte)0x13,
                (byte)-61, (byte)-21, (byte)-95, (byte)-106, (byte)-11, (byte)-103,
                (byte)-77, (byte)-61, (byte)-82, (byte)0x1B, (byte)-27, (byte)-112,
                (byte)-102, (byte)-14, (byte)0x5F, (byte)0x17, (byte)-37, (byte)-72,
                (byte)-123, (byte)0x31, (byte)0x11, (byte)-112, (byte)0x3F, (byte)0x23,
                (byte)0x52, (byte)-65
            },
            new byte[]{
                (byte)-39, (byte)-77, (byte)0x46, (byte)-4, (byte)-58, (byte)-18,
                (byte)0x53, (byte)-63, (byte)0x0C, (byte)0x0B, (byte)0x0B, (byte)-23
            },
            new byte[]{
                (byte)0x16, (byte)-98, (byte)0x72, (byte)-116, (byte)-41, (byte)-123,
                (byte)0x71, (byte)0x3F, (byte)0x77, (byte)-70, (byte)-52, (byte)-126,
                (byte)0x40, (byte)-20, (byte)0x70, (byte)-26
            }
        ));
        encryptedData.put(CredentialKey.DATABASE_URL, new EncryptedData(
            new byte[]{
                (byte)0x78, (byte)-53, (byte)-117, (byte)-111, (byte)-10, (byte)0x0A,
                (byte)0x10, (byte)-124, (byte)-19, (byte)-67, (byte)-120, (byte)0x65,
                (byte)0x28, (byte)0x48, (byte)-51, (byte)-67, (byte)-73, (byte)-11,
                (byte)0x5F, (byte)-56, (byte)0x23, (byte)-59, (byte)-31, (byte)-104,
                (byte)0x39, (byte)0x7E, (byte)-106, (byte)-110, (byte)0x64, (byte)-116,
                (byte)-54, (byte)0x10, (byte)0x2F, (byte)-77, (byte)-13, (byte)-75,
                (byte)0x36, (byte)0x16, (byte)0x3B, (byte)-53, (byte)0x4B, (byte)0x08,
                (byte)-117, (byte)0x0E
            },
            new byte[]{
                (byte)0x73, (byte)-5, (byte)0x50, (byte)0x22, (byte)-95, (byte)-76,
                (byte)0x00, (byte)-78, (byte)-128, (byte)0x40, (byte)-71, (byte)-104
            },
            new byte[]{
                (byte)-3, (byte)0x41, (byte)-107, (byte)0x39, (byte)-92, (byte)-110,
                (byte)0x23, (byte)0x25, (byte)-71, (byte)-7, (byte)0x79, (byte)-20,
                (byte)-128, (byte)-115, (byte)-57, (byte)0x32
            }
        ));
        encryptedData.put(CredentialKey.JWT_SECRET, new EncryptedData(
            new byte[]{
                (byte)-55, (byte)-87, (byte)0x1A, (byte)0x31, (byte)0x0C, (byte)0x3C,
                (byte)0x73, (byte)-1, (byte)-111, (byte)-19, (byte)0x2A, (byte)-105,
                (byte)0x51, (byte)0x12, (byte)-126, (byte)0x2B, (byte)-118, (byte)0x38,
                (byte)-10, (byte)-4, (byte)0x1B, (byte)0x54, (byte)0x66, (byte)-19,
                (byte)-98, (byte)0x5A, (byte)-85, (byte)0x7E, (byte)-21
            },
            new byte[]{
                (byte)-107, (byte)0x7F, (byte)-90, (byte)0x76, (byte)0x0E, (byte)-3,
                (byte)-120, (byte)-6, (byte)0x58, (byte)-34, (byte)-62, (byte)-85
            },
            new byte[]{
                (byte)-66, (byte)-102, (byte)0x00, (byte)0x2D, (byte)0x2E, (byte)-79,
                (byte)0x7F, (byte)0x19, (byte)-1, (byte)0x74, (byte)-59, (byte)-28,
                (byte)-120, (byte)-31, (byte)-111, (byte)0x0B
            }
        ));
        encryptedData.put(CredentialKey.STRIPE_KEY, new EncryptedData(
            new byte[]{
                (byte)0x4C, (byte)0x27, (byte)0x5E, (byte)-63, (byte)-76, (byte)-8,
                (byte)0x62, (byte)0x2C, (byte)-64, (byte)-109, (byte)-79, (byte)0x35,
                (byte)0x0C, (byte)0x62, (byte)0x25, (byte)0x40, (byte)0x5B, (byte)0x7B,
                (byte)-79, (byte)-43, (byte)-99, (byte)0x4A, (byte)0x70, (byte)-110,
                (byte)0x6C, (byte)0x78, (byte)-80
            },
            new byte[]{
                (byte)0x08, (byte)0x77, (byte)0x66, (byte)-88, (byte)-114, (byte)-1,
                (byte)-60, (byte)0x47, (byte)-52, (byte)-104, (byte)-124, (byte)-48
            },
            new byte[]{
                (byte)-80, (byte)0x6C, (byte)0x33, (byte)-44, (byte)0x50, (byte)-112,
                (byte)0x29, (byte)-19, (byte)-96, (byte)0x28, (byte)-14, (byte)-83,
                (byte)-78, (byte)0x31, (byte)-93, (byte)0x49
            }
        ));

        // Initialize key components
        keyComponents = new byte[][]{
            new byte[]{(byte)0x7B, (byte)-93, (byte)0x27, (byte)-27},
            new byte[]{(byte)-72, (byte)0x35, (byte)0x53, (byte)0x07},
            new byte[]{(byte)0x29, (byte)0x78, (byte)-66, (byte)0x54},
            new byte[]{(byte)-4, (byte)0x03, (byte)-11, (byte)0x36},
            new byte[]{(byte)0x17, (byte)0x40, (byte)-30, (byte)0x09},
            new byte[]{(byte)-10, (byte)-36, (byte)0x7B, (byte)-9},
            new byte[]{(byte)0x6C, (byte)0x46, (byte)0x22, (byte)0x6B},
            new byte[]{(byte)0x53, (byte)-119, (byte)-110, (byte)-99},
        };
    }

    public static String decrypt(CredentialKey key) {
        EncryptedData encrypted = encryptedData.get(key);
        if (encrypted == null) return null;
        
        try {
            // Reconstruct key
            byte[] keyData = reconstructKey();
            SecretKeySpec secretKey = new SecretKeySpec(keyData, "AES");
            
            // Decrypt
            Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
            GCMParameterSpec gcmSpec = new GCMParameterSpec(128, encrypted.nonce);
            cipher.init(Cipher.DECRYPT_MODE, secretKey, gcmSpec);
            
            byte[] combined = concatenate(encrypted.data, encrypted.tag);
            byte[] decrypted = cipher.doFinal(combined);
            
            return new String(decrypted, StandardCharsets.UTF_8);
        } catch (Exception e) {
            return null;
        }
    }
    
    private static byte[] reconstructKey() {
        int totalLength = 0;
        for (byte[] component : keyComponents) {
            totalLength += component.length;
        }
        
        byte[] result = new byte[totalLength];
        int offset = 0;
        for (byte[] component : keyComponents) {
            System.arraycopy(component, 0, result, offset, component.length);
            offset += component.length;
        }
        return result;
    }
    
    private static byte[] concatenate(byte[] a, byte[] b) {
        byte[] result = new byte[a.length + b.length];
        System.arraycopy(a, 0, result, 0, a.length);
        System.arraycopy(b, 0, result, a.length, b.length);
        return result;
    }
    
    // Optional: Cached decryption
    private static final Map<CredentialKey, String> cache = new HashMap<>();
    
    public static String decryptCached(CredentialKey key) {
        String cached = cache.get(key);
        if (cached != null) return cached;
        
        String decrypted = decrypt(key);
        if (decrypted != null) {
            cache.put(key, decrypted);
        }
        return decrypted;
    }
    
    public static void clearCache() {
        cache.clear();
    }
}