from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="credential-code-utility",
    version="0.1.0",
    author="credential-code",
    description="A utility library for decrypting .creds files generated by credential-code",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/credential-code",
    py_modules=["credential_code_utility"],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.6",
    install_requires=[
        "cryptography>=3.0",
    ],
)